package io.gridgo.core.support;

public enum LifecycleType {

    CONTEXT_STARTED,
    CONTEXT_STOPPED,
    GATEWAY_OPENED,
    GATEWAY_CLOSED,
    GATEWAY_STARTED,
    GATEWAY_STOPPED,
    CONNECTOR_ATTACHED,
    CONNECTOR_STARTED,
    CONNECTOR_STOPPED,
    COMPONENT_ATTACHED,
    COMPONENT_STARTED,
    COMPONENT_STOPPED
}
